extern crate bindgen;

use std::path::{PathBuf};
use std::{env, fs};

const ZSH_BUILD_DIR: &'static str = "zsh_build";

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());

    let Locations { wrapper, includes } = zsh_prebuild(&root, &out_path);

    println!("cargo:rerun-if-changed=include/zsh/.git/HEAD");
    println!("cargo:rerun-if-changed=.git/modules/zsh/HEAD");

    let bindings = bindgen::Builder::default()
        .header(wrapper)
        .clang_args(includes.iter().map(|p| format!("-I{}", p.display())))
        .clang_arg("-DMODULE")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .derive_default(true)
        .wrap_unsafe_ops(true)
        .generate()
        .expect("Unable to generate bindings");

    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}

struct Locations {
    wrapper: String,
    includes: Vec<PathBuf>,
}

impl Locations {
    fn from(wrapper: &PathBuf, src_dir: PathBuf, build_dir: PathBuf) -> Self {
        Self {
            wrapper: wrapper.to_str().unwrap().to_owned(),
            includes: vec![
                src_dir.join("Src"),
                // src_dir.join("Src/Builtins"),
                // src_dir.join("Src/Modules"),
                src_dir.join("Src/Zle"),
                build_dir.join("Src"),
            ],
        }
    }
}

fn zsh_prebuild(root: &PathBuf, out_path: &PathBuf) -> Locations {
    let src_dir = root.join("include/zsh");
    let target_dir = get_target_dir(&out_path).expect("Failed to determine Cargo target directory");
    let build_dir = target_dir.join(ZSH_BUILD_DIR);

    let wrapper = build_dir.join("wrapper.h");

    if !build_dir.exists() {
        fs::create_dir_all(&build_dir).expect("Failed to create build directory");
    }

    let sha = fs::read_to_string(root.join(".git/modules/zsh/HEAD"))
        .or_else(|_| fs::read_to_string(src_dir.join(".git/HEAD")))
        .unwrap_or_default();
    let stamp = build_dir.join("configure.stamp");
    let needs_configure = fs::read_to_string(&stamp)
        .map(|s| s.trim() != sha.trim())
        .unwrap_or(true);

    if needs_configure {
        commands::autoreconf(&src_dir);
        commands::configure(&src_dir, &build_dir);
        commands::make_prep(&build_dir);
        commands::make_headers(&build_dir);

        let mut content = String::from("/* Generated by build.rs — do not edit */\n");
        let pattern = format!("{}/Src/**/*.mdh", build_dir.display());
        glob::glob(&pattern)
            .unwrap()
            .filter_map(Result::ok)
            .map(|path| path.strip_prefix(&build_dir).unwrap().to_path_buf())
            .for_each(|path| {
                content.push_str(&format!("#include \"{}\"\n", path.display()));
            });

        fs::write(&wrapper, content).unwrap();
        fs::write(&stamp, &sha).unwrap();
    }

    Locations::from(&wrapper, src_dir, build_dir)
}

mod commands {
    use std::{path::PathBuf, process::Command};

    /// Generate configure script if submodule doesn't include it
    pub(super) fn autoreconf(submod: &PathBuf) {
        Command::new("autoreconf")
            .arg("-fi")
            .current_dir(&submod)
            .run()
    }

    // Run configure out-of-tree — produces config.h, Makefiles, signames.h, etc.
    // No --disable-dynamic: we need module subdirs to exist for proto generation
    pub(super) fn configure(submod: &PathBuf, zsh_build: &PathBuf) {
        println!("cargo:warning=Starting slow task...");
        Command::new(submod.join("configure").canonicalize().unwrap())
            .arg(format!("--srcdir={}", submod.display()))
            .arg("--disable-dynamic")
            .current_dir(&zsh_build)
            .run()
    }

    /// prep: runs mkmakemod.sh, creates Zle/ Builtins/ etc. subdirs in build tree
    pub(super) fn make_prep(zsh_build: &PathBuf) {
        Command::new("make")
            .arg("-C")
            .arg("Src")
            .arg("prep")
            .current_dir(&zsh_build)
            .run()
    }

    /// proto: runs makepro.awk over all .c files, generates .epro files
    pub(super) fn make_headers(zsh_build: &PathBuf) {
        Command::new("make")
            .arg("-C")
            .arg("Src")
            .arg("headers")
            .arg("-j")
            .current_dir(&zsh_build)
            .run()
    }

    trait RunCommand {
        fn run(&mut self);
    }

    impl RunCommand for Command {
        fn run(&mut self) {
            let status = self.status().expect("failed to spawn command");
            assert!(status.success(), "command failed: {:?}", self);
        }
    }
}

fn get_target_dir(out_dir: &PathBuf) -> Option<PathBuf> {
    let profile = std::env::var("PROFILE").expect("PROFILE environment variable not set");
    let mut sub_path = out_dir.as_path();
    while let Some(parent) = sub_path.parent() {
        if parent.ends_with(&profile) {
            return parent.parent().map(|p| p.to_path_buf());
        }
        sub_path = parent;
    }
    None
}
