name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
        cargo_flags:
          - "--no-default-features"
          - "--all-features"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install ZSH
        if: runner.os == 'Linux'
        run: sudo apt-get install zsh

      - name: ⚡ Cache cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/zsh-src
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 🔨 Build
        run: cargo build --all ${{ matrix.cargo_flags }}
        
      - name: 🧪 Test
        run: cargo test --all ${{ matrix.cargo_flags }}